/**
 * Writes THIRD-PARTY.md: the licence of every package the app ships.
 *
 *     npm run notices
 *
 * The list is the studio's production dependency tree (what Vite bundles into
 * the app) plus Electron, which the installer carries. Electron's own and
 * Chromium's licence files are copied in by the packager, so Electron gets a
 * line here and not its text. Run it after any change to the dependencies.
 */

import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const MODULES = join(ROOT, "node_modules");

// Through npm's own script when run by npm, so Windows needs no shell.
const args = ["ls", "--omit=dev", "--all", "--json", "--workspace", "@jamcalc/studio"];
const npm = process.env.npm_execpath;
const tree = JSON.parse(
  npm
    ? execFileSync(process.execPath, [npm, ...args], { cwd: ROOT, encoding: "utf8" })
    : execFileSync("npm", args, { cwd: ROOT, encoding: "utf8", shell: process.platform === "win32" }),
);

/** Every package below the studio, once each. */
const names = new Set();
(function walk(deps) {
  for (const [name, node] of Object.entries(deps ?? {})) {
    if (name.startsWith("@jamcalc/") || names.has(name)) continue;
    names.add(name);
    walk(node.dependencies);
  }
})(tree.dependencies?.["@jamcalc/studio"]?.dependencies);

function licenceText(dir) {
  const file = readdirSync(dir).find((f) => /^licen[cs]e(\.(md|txt))?$/i.test(f));
  return file ? readFileSync(join(dir, file), "utf8").trim() : undefined;
}

/** Who to credit when there is no licence file: the author, else the source. */
function origin(pkg) {
  const a = typeof pkg.author === "string" ? pkg.author : pkg.author?.name;
  if (a) return ` Copyright ${a}.`;
  const repo = typeof pkg.repository === "string" ? pkg.repository : pkg.repository?.url;
  return repo ? ` Source: ${repo.replace(/^git\+/, "")}.` : "";
}

const packages = [...names].sort().map((name) => {
  const dir = join(MODULES, name);
  const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  return {
    name,
    version: pkg.version,
    licence: typeof pkg.license === "string" ? pkg.license : "see text",
    // A package with no licence file still declares one; credit its author,
    // or failing that where it comes from.
    text:
      licenceText(dir) ??
      `${pkg.license} licence, as declared by the package.${origin(pkg)}`,
  };
});

const electron = JSON.parse(readFileSync(join(MODULES, "electron", "package.json"), "utf8"));
if (!existsSync(join(MODULES, "electron", "dist", "LICENSES.chromium.html"))) {
  console.warn("warning: Electron's Chromium licence file is missing; the installer would ship without it");
}

const lines = [
  "# Third-party software",
  "",
  "jamCalc is MIT-licensed ([LICENSE](LICENSE)) and includes the software below,",
  "each under its own licence. Generated by `npm run notices`; do not edit by hand.",
  "",
  "| Package | Version | Licence |",
  "|---|---|---|",
  ...packages.map((p) => `| ${p.name} | ${p.version} | ${p.licence} |`),
  `| electron | ${electron.version} | MIT, plus Chromium's licences |`,
  "",
  "The desktop app is built on Electron, which includes Chromium. Their",
  "licences are installed beside the program as `LICENSE.electron.txt` and",
  "`LICENSES.chromium.html`.",
  "",
  ...packages.flatMap((p) => ["---", "", `## ${p.name} ${p.version}`, "", "```", p.text, "```", ""]),
];

writeFileSync(join(ROOT, "THIRD-PARTY.md"), lines.join("\n"));
console.log(`THIRD-PARTY.md: ${packages.length} packages, plus Electron`);
